### PR TITLE
Restore documentation generation

### LINKED ISSUE #78: Doc generation no longer works
We expect

    .\build GenerateDocs

to work.  Or this with updated `dotnet fake`:

    .\build target GenerateDocs

Both fail.

### PR DESCRIPTION
**Pull request by zyzhu**
Fix #78

Though FSFormatting.createDocs finally supports passing fsieval, XPlot doc needs to register custom format for various plot html format by calling formatters.fsx. I restored generates.fsx similar to Deedle and modified build.fsx.

All doc htmls are updated in this pull. Dependencies are updated as well.

### CODE REVIEW

**Comment by FoggyFinder** [comment]
So nice to see merged PR. Project isn't totally dead. Yay.

**Comment by dsyme** [comment]
Yes, @zyzhu is now a co-maintainer!  Thank you and welcome!

**Comment by zyzhu** [comment]
@FoggyFinder There are quite a lot of pending issues. Feel free to submit pull requests.

**Comment by zyzhu** [comment]
I have changed the script to release docs to gh-pages branch like other fsharp repos. Plotly chart generate random id whenever we run the doc generations. It shows too much noise in the master branch.

@dsyme Could you change the Github page to gh-pages branch? I do not have access to the settings.

**Comment by dsyme** [comment]
@zyzhu Done, thanks

**Comment by dharmaturtle** [comment]
The sample graphs on https://fslab.org/XPlot/ are no longer displaying: 

image

Associated docfile: https://github.com/fslaborg/XPlot/blob/master/docs/index.fsx

However, the docs on other files _are_ appearing, e.g. https://fslab.org/XPlot/chart/plotly-histograms.html

Does anyone know why this might be occurring?

---

I'm trying to generate a graph for [another repository's](https://hedgehogqa.github.io/fsharp-hedgehog/) docs, and I'm seeing this kind of output:

image

My ulterior motive is to try to figure out why this is occurring, but in debugging my issue I arrived here :)

**Comment by cartermp** [comment]
Indeed, it seems like something is busted. Docs gen is something I'll also have to look at again, as the tool has undergone many major changes and thus needs a big redo.

**Pull request merged**
