### PR TITLE
Adding Candlestick to Plotly

### PR DESCRIPTION
**Pull request by queil**
I needed candlestick charts in Plotly and I thought it could be a useful addition.

### CODE REVIEW

**Comment by queil** [comment]
@tpetricek: Is there any chance for the PR to be reviewed any time soon?

**Comment by tpetricek** [comment]
Thanks for the ping - I'm doing the release right now.

**Comment by queil** [comment]
Thank you.

**Comment by tpetricek** [comment]
Oops, turns out only @dsyme and @TahaHachana have the rights to push a new version to NuGet! I'll ask them to add me and release it as soon as I can. Thanks so much for the contribution!

**Comment by TahaHachana** [comment]
@tpetricek Added you as an owner of the packages and the changes look good to me.

**Pull request merged**
