### PR TITLE
Update dependencies and incorporate fsdocs into doc gen

### PR DESCRIPTION
**Pull request by cartermp**
* Dependencies update was necessary to start building some stuff out
* Docs need an overhaul but this at least incorporates fsdocs into the pipeline so things can iterate

### CODE REVIEW

**Comment by cartermp** [comment]
Ugh, running into this: https://github.com/fsharp/FAKE/issues/2515

**Comment by cartermp** [comment]
Okay, log file issue resolved. But now expecto is throwing missingmethodexception 🙃

**Comment by dsyme** [comment]
Hey are the docs published yet?  Was going to check through them to harvest new possible fsdocs improvements

**Comment by cartermp** [comment]
They're not. You can run the tool to verify the issues, though.

**Pull request merged**
