### PR TITLE
Fix documentations

### PR DESCRIPTION
**Pull request by zyzhu**
@cartermp This is a big pull. 

1. Essentially I've fixed various broken links and dlls of documentations. I followed samples from Plotly.Net and DiffSharp and generated documentation and notebooks through latest fsdocs. You may check out the page on my [fork](https://zyzhu.github.io/XPlot//index.html). The binder link on my page shall also work as I overrode the link to my fork as well.
2. Added `GenerateLocalDocs` in bulld.fsx to create docs on local machine with correct root to iterate pages quicker.
3. Follow some styles of DiffSharp and put navigation to the left.
4. Modified some wording to put Plotly before GoogleCharts as Plotly is more widely used. Interactive extension is also available already.
5. Though GoogleCharts does not have interactive extension yet, notebooks are generated as well. We just need to add extension in the future to display it in notebook.

I don't know how to add releasing docs directly into GH workflow. But we can still run `build target ReleaseDocs` locally to publish it. Let me know if you are ok with the changes as I can publish the pages.

### CODE REVIEW

**Review by cartermp — APPROVED** [review]
Splendid! The main issue I ran into on my own machine with fsdocs was that the _hide_ directive wasn't working. But I think it looks fine with the data set included.

**Comment by cartermp** [comment]
Feel free to publish the changes as well!

**Comment by cartermp** [comment]
I think we can perhaps modify the build definitions to just run `build target ReleaseDocs` on the CI server after a PR is merged. Should be a separate action though.

**Comment by zyzhu** [comment]
Published. Ideally documentation shall conditionally hide the raw dataset on html but keep it in the notebook so that it works interactively. But I did not figure out how.

I also tried to generate fsx through fsdocs directly, but I found the raw html charts from `include-it-raw` cannot be hidden in fsx files.

You may give it a spin and raise the issues on FSharp.Formatting separately.

**Pull request merged**
