### PR TITLE
Add static setters to KernelExtension.

### PR DESCRIPTION
**Pull request by nojaf**
In our corporate environment, we cannot access the public internet and would need to use our own CDN endpoint.

Similar to https://github.com/fslaborg/XPlot/pull/145,this allows us to set this.

### CODE REVIEW

**Comment by nojaf** [comment]
Hi @zyzhu and @cartermp,

Any chance this could make it in?
We are still using XPlot for some projects and can't easily upgrade.

**Review by cartermp — APPROVED** [review]

**Comment by cartermp** [comment]
ahhh FFS out of date .NET versions and fake

**Comment by nojaf** [comment]
@cartermp I replace FAKE with Fun.Build in https://github.com/fslaborg/XPlot/pull/181 to avoid the build problem.

**Comment by nojaf** [comment]
@cartermp the build is green now.

**Comment by nojaf** [comment]
Thanks @cartermp ! Any chance we could get a release with this?

**Comment by cartermp** [comment]
I was hoping to get in https://github.com/fslaborg/XPlot/pull/179#issuecomment-2075412557 first, let me see about this by end of day?

**Comment by jonsequitur** [comment]
There's an approach to custom formatters for .NET Interactive that's a bit simpler and doesn't require a reference to the .NET Interactive libraries, if that's interesting. 

https://github.com/dotnet/interactive/blob/main/docs/formatting.md#typeformattersourceattribute

**Comment by nojaf** [comment]
Any updates on this @cartermp?

**Comment by cartermp** [comment]
Done and done

**Comment by nojaf** [comment]
Thank you!

**Pull request merged**
