### PR TITLE
update .net interactive packages

### PR DESCRIPTION
**Pull request by colombod**
Updated to use latest public packages from .net interactive.
@cartermp can you check i did it correctly? Once merge can anyone publish latest versions?

### CODE REVIEW

**Review by cartermp — APPROVED** [review]
Should be good (you could argue that some of the other packages shouldn't need bumped assemblyinfo but it isn't harmfult o do it)

**Comment by cartermp** [comment]
Once green I will publish packages

**Comment by colombod** [comment]
> Once green I will publish packages

I am going to merge and delete the branch, can you publish the packages?

**Comment by cartermp** [comment]
yep yep

**Comment by cartermp** [comment]
Indexing on nuget as we speak

**Comment by colombod** [comment]
Nice

Dr Diego Colombo PhD

**Pull request merged**
