### PR TITLE
Magicmode

### PR DESCRIPTION
**Pull request by jackfoxy**
1) paket magic mode
2) dotnet SDK style projects
3) multitarget net45 and netstandard2.0

### CODE REVIEW

**Comment by jackfoxy** [comment]
Now Newtonsoft.Json also failing in VS 15.8 preview 4
The namespace or module 'Newtonsoft' is not defined.
 
Added 
'''`<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>'''`
And it once again builds debug net45 and netstandard2.0 in VS
Build script builds release net45, but still fails on netstandard2.0
 
VS has no problem building release netstandard2.0
 
very strange

**Comment by dsyme** [comment]
@jackfoxy are you merging with master or would you like me to do it? thanks

**Comment by jackfoxy** [comment]
updated the PR with binding redirects

**Comment by jackfoxy** [comment]
@dsyme  I don't know what other branch to send PR to
I was responding to your request https://github.com/fslaborg/FsLab/issues/137#issuecomment-406582666
As you see from my comments, still a problem with build script. I'm working on it now. Happy to have other eyes on it.

**Comment by jackfoxy** [comment]
@dsyme  this is almost certainly a Paket problem, since I can get my changes to build with "native" nuget.

https://github.com/fsprojects/Paket/issues/3309

I'll give paket some time to respond before I update this PR.

**Comment by jackfoxy** [comment]
@dsyme 
1) merged with prior changes to master
2) paket issue resolved (user error)

ready to merge with master

**Comment by jackfoxy** [comment]
fixed the Travis build

**Pull request merged**
