### PR TITLE
.NET Standard 2.0 only and cleanup

### PR DESCRIPTION
**Pull request by cartermp**
I couldn't find any references to .NET Framework-specific code, so it's safe to go .NET Standard 2.0 only.

The only affected project/package here is XPlot.D3, which still had a `net45` target. Since we've dropped that in FSharp.Core, I think it's fine to also do that here. XPlot all-up can just be .NET Standard 2.0 moving forward.

Additionally, every `net472` target was redundant. `net471` and higher can reference .NET Standard 2.0 components, so there's no need to target .NET Framework unless you're going after a lower .NET Framework version.

Some minor cleanup in the project files too. And removes a dangling `packages.config`.

### CODE REVIEW

**Review by colombod — APPROVED** [review]
makes sense as the project also targeted different desktop sdks

**Comment by dsyme** [comment]
Wonderful!!

I've made you both co-maintainers so you don't get blocked, will add you to nugets too

**Comment by dsyme** [comment]
@colombod @cartermp can you send me your nuget IDs please?

**Comment by cartermp** [comment]
@dsyme  https://www.nuget.org/profiles/cartermp

**Comment by dsyme** [comment]
@cartermp 0 packages? :) I wasn't sure if it was you! :)

**Comment by colombod** [comment]
@dsyme https://www.nuget.org/profiles/colombod

**Comment by dsyme** [comment]
OK, I've added you both to all 5 pacakges should you need to update them.  @zyzhu can help with any recent packaging publication problems

**Comment by dsyme** [comment]
(you have to accept all 5 invites)

**Comment by cartermp** [comment]
@zyzhu any objections?

**Comment by cartermp** [comment]
Actually let's hold on this, running `build.sh build` resulted in a failure expecting a `net45` target.

**Comment by cartermp** [comment]
Okay, local build works with these changes

**Comment by zyzhu** [comment]
travis and appveyor don't support netcore 3.0 yet.

BTW, that XPlot.GoogleCharts.Tests project looks like a redundant project. Those fsx files exist in  src\XPlot.GoogleCharts\tests too.

There are no automatic tests on XPlot. There are only fsx files to be run to see whether charts are rendered in browser.

**Comment by zyzhu** [comment]
I checked plotly.js repo the other day. Their tests saved all plotly pictures in png and compare the results with their baseline pictures.
https://github.com/plotly/plotly.js/tree/master/test/image

**Comment by cartermp** [comment]
I’ll adjust this.

Later this week I’ll look into moving to Azure DevOps. And refactoring tests :)

**Pull request merged**
